# Generated by Django 3.2.5 on 2021-08-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='user',
        ),
    ]
