# Generated by Django 3.2.5 on 2021-08-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210628_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
