# Generated by Django 3.2.6 on 2021-08-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20210820_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='password',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
    ]
